name: Update Contributors in README

permissions:
  contents: write
  
on:
  push:
    paths:
      - "portfolio/**.md"
      - ".github/workflows/update-contributors.yml"
  pull_request:
    paths:
      - "portfolio/**.md"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Update README.md
        run: node .github/scripts/update-readme.js

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: auto-update contributor list"
